import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import Card from "../components/Card";
import { Content, GetContentsData } from "./api/api";

const Home: NextPage = () => {
  const [users, setUsers] = useState<string[]>([""]);
  const [user, setUser] = useState<string>("");
  const [contents, setContents] = useState<Content[]>([]);
  const { loading, getFn, error, response } = GetContentsData();

  useEffect(() => {
    getFn("papaiaMK2");
  }, []);

  useEffect(() => {
    if (!response) {
      return;
    }

    setContents(response.data);
    console.log(response.data);
  }, [response]);

  const testList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  return (
    <div className="text-white bg-gray-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <p className="py-4 text-2xl text-center">Twitter 画像だけ</p>
      </div>

      <div className="flex flex-wrap justify-center content-start mt-4">
        {testList.map((num) => {
          return <Card text="testetset" key={num} />;
        })}
      </div>
    </div>
  );
};

export default Home;
