import type { NextPage } from "next";
import Head from "next/head";

import Card from "../components/Card";

const Home: NextPage = () => {
  const testList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  return (
    <div className="text-white bg-gray-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <p className="py-4 text-2xl text-center">Twitter 画像だけ</p>
      </div>

      <div className="flex flex-wrap justify-center content-start mt-4">
        {testList.map((num) => {
          return <Card text="testetset" key={num} />;
        })}
      </div>
    </div>
  );
};

export default Home;
