import { CogIcon } from "@heroicons/react/solid";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import store from "store";
import { v4 as uuidv4 } from "uuid";

import Card from "../components/Card";
import { User } from "../shared/types";
import { Content, GetContentsData } from "./api/api";

const Home: NextPage = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [contents, setContents] = useState<Content[]>([]);
  const { loading, getFn, error, response } = GetContentsData();

  useEffect(() => {
    console.log(store.get("users"));
    getFn("papaiaMK2,kondou0809");
  }, []);

  useEffect(() => {
    if (!response) {
      return;
    }

    setContents(response.data);
  }, [response]);

  return (
    <div className="text-white bg-gray-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <p className="py-4 text-2xl text-center">Twitter 画像だけ</p>
      </div>

      {loading && <p>Loading</p>}

      {!loading && (
        <div className="flex flex-wrap justify-center content-start mt-4">
          {contents.map((content) => {
            return <Card content={content} key={content.image_url} />;
          })}
        </div>
      )}

      {/* <div className="fixed bottom-0 right-0 m-3">
        <button className="rounded h-12 w-12">検索</button>
      </div> */}

      <div className="fixed bottom-0 left-0 p-1 m-4 bg-gray-400 rounded-full shadow-xl">
        <Link href="/config">
          <CogIcon className="w-10 h-10 rounded" />
        </Link>
      </div>
    </div>
  );
};

export default Home;
